name: CI Pipeline

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - "**"
    tags:
      - "v*.*.*"
  pull_request:

jobs:
  # Build, Test and Push Docker image
  tests:
    name: Build, Test and Push Docker image
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Extract Docker metadata
      - name: Set up Docker metadata
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: ${{ github.repository }}/test_image
      # Push Dokcer image
      - name: Push Docker image
        if: ${{secrets.DOCKERHUB_USER}} != null
        run: |
          echo ${{ secrets.DOCKERHUB_USER }}
          for t in ${{ steps.docker_meta.outputs.tags }}; do
            echo ${t}
          done
      
